### ISSUE TITLE
[Feature Request] Add "mongodb" to tags in service binding

### ISSUE THREAD

**Issue by claassen** [mongodb/atlas-osb#16]
Currently service bindings do not provide any tags in VCAP_SERVICES, e.g.:

```
"mongodb-atlas-azure": [
        {
          "label": "mongodb-atlas-azure",
          "provider": null,
          "plan": "M10-small",
          "name": "app-health-check-db",
          "tags": [],
          "instance_name": "app-health-check-db",
          "binding_name": null,
          "credentials": {
            ...
          },
          "syslog_drain_url": null,
          "volume_mounts": []
        }
      ],
```

This is breaking some functionality for certain Spring Boot apps where it uses the tags to identify the MongoDB service instance.

Requesting that "mongodb" should be added to the "tags" array, e.g.:

"mongodb-atlas-azure": [
        {
          "label": "mongodb-atlas-azure",
          "provider": null,
          "plan": "M10-small",
          "name": "app-health-check-db",
          "tags": ["mongodb"],
          "instance_name": "app-health-check-db",
          "binding_name": null,
          "credentials": {
            ...
          },
          "syslog_drain_url": null,
          "volume_mounts": []
        }
      ],
```

**Comment by vasilevp** [comment]
We can make this configurable just like every other service parameter - I'll get the feature out tomorrow.

Meanwhile you can use user-provided tags to unblock your testing:
```
cf create-service <...> -t "mongodb"
```

**Comment by vasilevp** [comment]
This will be including in upcoming release
