### ISSUE TITLE
Support for custom usernames

### ISSUE THREAD

**Issue by joncashe** [mongodb/atlas-osb#35]
Hello

 first I wanted to thank you for the implementation I have been using this version and one of things we were expecting its to use custom names for the cluster and the usernames instead of guids (for the servicebinding)

so far the cluster custom name seems to be fixed but why is it necessary to use bindingid for the username (https://github.com/mongodb/atlas-osb/blob/master/pkg/broker/binding_operations.go#L46)? 
 is there any major reason im missing? i know that the same bindingid its also use to delete the user(https://github.com/mongodb/atlas-osb/blob/master/pkg/broker/binding_operations.go#L149) but wanted to know if this its expected to be address at some point 

thanks

**Comment by jasonmimick** [comment]
Hi @joncashe,

Thanks for your feedback and for reporting this issue. As you've correctly identified, the current implementation is far from ideal. [Background: current implementation is based upon a legacy service broker dependencies our main customer has with the a deprecated service broker].

We are investigating better support for any database username which MongoDB Atlas allows.
Please expect an update with proposed design for review within 1 week.

Thanks-

**Comment by jamesbroadhead** [comment]
We have decided not to implement this feature for the time being. Please get in touch if this is an issue for you
