### ISSUE TITLE
updating instance size does not work

### ISSUE THREAD

**Issue by tanjoht** [mongodb/atlas-osb#5]
Issue: The Update Instance size doesn't work properly. The cf command fails but the operation is successfully carried out on Atlas UI

Command: cf update-service testosb15 -c '{"cluster":{"ProviderSettings":{"InstanceSizeName":"M20"}}}'

Error: Updating service instance testosb15 as

admin...

FAILED

Server error, status code: 502, error code: 10001, message: Service broker error: {"error":"value not found: '66fb9133-9f0d-4d99-a287-4cfbb1c497d6'"}

Logs:

2020-08-25T15:07:58.09-0700 [APP/PROC/WEB/0] OUT {"level":"error","ts":1598393278.098033,"caller":"broker/instance_operations.go:243","msg":"Error delete from state","func":"Update","err":"{\"error\":\"value

not found: '66fb9133-9f0d-4d99-a287-4cfbb1c497d6'\"}","errVerbose":"{\"error\":\"value not found: '66fb9133-9f0d-4d99-a287-4cfbb1c497d6'\"}\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/mongodbrealm.CheckResponse\n\t/tmp/app/pkg/mongodbrealm/mongodbrealm.go:417\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/mongodbrealm.(*Client).do\n\t/tmp/app/pkg/mongodbrealm/mongodbrealm.go:377\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/mongodbrealm.(*Client).Do\n\t/tmp/app/pkg/mongodbrealm/mongodbrealm.go:328\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/mongodbrealm.(*RealmValuesServiceOp).Delete\n\t/tmp/app/pkg/mongodbrealm/realm_values.go:184\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/broker/statestorage.(*RealmStateStorage).DeleteOne\n\t/tmp/app/pkg/broker/statestorage/statestorage.go:208\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/broker.Broker.Update\n\t/tmp/app/pkg/broker/instance_operations.go:241\ngithub.com/pivotal-cf/brokerapi/handlers.APIHandler.Update\n\t/home/vcap/go/pkg/mod/github.com/pivotal-cf/brokerapi@v5.1.0+incompatible/handlers/update.go:43\nnet/http.HandlerFunc.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2007\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/broker.authMiddleware.func1.1\n\t/tmp/app/pkg/broker/auth.go:42\nnet/http.HandlerFunc.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/vcap/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:1890\nruntime.goexit\n\t/tmp/contents622812680/deps/0/go1.13.12/src/runtime/asm_amd64.s:1357","instanceID":"66fb9133-9f0d-4d99-a287-4cfbb1c497d6","stacktrace":"github.com/mongodb/mongodb-atlas-service-broker/pkg/broker.Broker.Update\n\t/tmp/app/pkg/broker/instance_operations.go:243\ngithub.com/pivotal-cf/brokerapi/handlers.APIHandler.Update\n\t/home/vcap/go/pkg/mod/github.com/pivotal-cf/brokerapi@v5.1.0+incompatible/handlers/update.go:43\nnet/http.HandlerFunc.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2007\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/broker.authMiddleware.func1.1\n\t/tmp/app/pkg/broker/auth.go:42\nnet/http.HandlerFunc.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/vcap/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:1890"}

   2020-08-25T15:07:58.09-0700 [APP/PROC/WEB/0] OUT {"level":"error","ts":1598393278.098206,"caller":"app/logger.go:75","msg":"unknown-error","error":"{\"error\":\"value not found: '66fb9133-9f0d-4d99-a287-4cfbb1c497d6'\"}","errorVerbose":"{\"error\":\"value

not found: '66fb9133-9f0d-4d99-a287-4cfbb1c497d6'\"}\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/mongodbrealm.CheckResponse\n\t/tmp/app/pkg/mongodbrealm/mongodbrealm.go:417\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/mongodbrealm.(*Client).do\n\t/tmp/app/pkg/mongodbrealm/mongodbrealm.go:377\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/mongodbrealm.(*Client).Do\n\t/tmp/app/pkg/mongodbrealm/mongodbrealm.go:328\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/mongodbrealm.(*RealmValuesServiceOp).Delete\n\t/tmp/app/pkg/mongodbrealm/realm_values.go:184\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/broker/statestorage.(*RealmStateStorage).DeleteOne\n\t/tmp/app/pkg/broker/statestorage/statestorage.go:208\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/broker.Broker.Update\n\t/tmp/app/pkg/broker/instance_operations.go:241\ngithub.com/pivotal-cf/brokerapi/handlers.APIHandler.Update\n\t/home/vcap/go/pkg/mod/github.com/pivotal-cf/brokerapi@v5.1.0+incompatible/handlers/update.go:43\nnet/http.HandlerFunc.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2007\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/broker.authMiddleware.func1.1\n\t/tmp/app/pkg/broker/auth.go:42\nnet/http.HandlerFunc.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/vcap/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:1890\nruntime.goexit\n\t/tmp/contents622812680/deps/0/go1.13.12/src/runtime/asm_amd64.s:1357","stacktrace":"main.(*LagerZapLogger).Error\n\t/tmp/app/logger.go:75\ngithub.com/pivotal-cf/brokerapi/handlers.APIHandler.Update\n\t/home/vcap/go/pkg/mod/github.com/pivotal-cf/brokerapi@v5.1.0+incompatible/handlers/update.go:50\nnet/http.HandlerFunc.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2007\ngithub.com/mongodb/mongodb-atlas-service-broker/pkg/broker.authMiddleware.func1.1\n\t/tmp/app/pkg/broker/auth.go:42\nnet/http.HandlerFunc.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/vcap/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/tmp/contents622812680/deps/0/go1.13.12/src/net/http/server.go:1890"}

   2020-08-25T15:07:58.09-0700 [RTR/2] OUT mongodb-atlas-osb.apps.use.sandbox.pcf.manulife.com - [2020-08-25T22:07:53.858682992Z] "PATCH /v2/service_instances/66fb9133-9f0d-4d99-a287-4cfbb1c497d6?accepts_incomplete=true

HTTP/1.1" 500 748 90 "-" "HTTPClient/1.0 (2.8.3, ruby 2.5.5 (2019-03-15))" "10.234.254.40:59964" "10.234.250.38:61074" x_forwarded_for:"10.234.250.29, 10.234.254.40" x_forwarded_proto:"https" vcap_request_id:"e96c9457-fe45-4d0d-79ba-f33925d37192" response_time:4.240590

gorouter_time:0.000843 app_id:"f9337735-3092-4b72-980b-a8cde7cec038" app_index:"0" x_cf_routererror:"-" x_b3_traceid:"16d91c508f42ef65" x_b3_spanid:"16d91c508f42ef65" x_b3_parentspanid:"-" b3:"16d91c508f42ef65-16d91c508f42ef65"

**Comment by jasonmimick** [comment]
Hi-

We've completed initial triage of this issue and will be able to provide a fix first thing tomorrow morning. 
The error is coming from a failure to clean up an obsolete state from the broker instance state store. This does not effect any aspect of the actual Atlas cluster and should not cause any further issues.

The scope/impact of this issue should be minimal, since the fix will be isolated to this background state mgmt and not effect the main broker workflows.

**Comment by tanjoht** [comment]
THis is the status of the cf service after the error (the cluster is indeed updated on atlas)

Showing status of last operation from service test-osb-small...

status:    update failed
message:   Service broker error: {"error":"value not found: '25ddd637-7e63-47e5-b35c-34cfe1cc08ee'"}

**Comment by jasonmimick** [comment]
Update-

We're still actively working on this issue. It seems that the `update-service` call has uncovered some nuances in the format of the JSON we get back from the Realm app which stores the state for each service instance. The issue cause's the golang parsers to fail to decode things properly, as extJSON is returned rather than regular JSON.
We have a patch test in progress and will provide updates soon as possible.
