### ISSUE TITLE
Updating service instance after being renamed fails with "Cannot change name of cluster during an update"

### ISSUE THREAD

**Issue by claassen** [mongodb/atlas-osb#8]
Steps to reproduce:

1. Create service instance

```bash
cf create-service mongodb-atlas-azure M10-small app-health-check-db-new
```

2. Rename service instance 

```bash
cf rename-service app-health-check-db-new app-health-check-db
```

3. Try to update service instance

```bash
cf update-service app-health-check-db -c ‘{“cluster”:{“ProviderSettings”:{“InstanceSizeName”:“M20"}}}’
```

Step 3 results in error:

FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/5f452ed36ec7600ac9616ffb/clusters/app-health-check-db-new: 400 (request "Bad Request") Cannot change name of cluster during an update.

**Comment by tanjoht** [comment]
does not work still

macC02XK673JG5L:atlas-osb-broker-pipeline tanjoht$ cf cs mongodb-atlas-azure M10-small testrename1
Creating service instance testrename1 in org system / space atlas-osb as admin...
OK

Create in progress. Use 'cf services' or 'cf service testrename1' to check operation status.

macC02XK673JG5L:atlas-osb-broker-pipeline tanjoht$ cf rename-service testrename1 testrename2
Renaming service testrename1 to testrename2 in org system / space atlas-osb as admin...
OK


macC02XK673JG5L:atlas-osb-broker-pipeline tanjoht$ cf update-service testrename2 -c '{"cluster":{"ProviderSettings":{"InstanceSizeName":"M20"}}}'
Updating service instance testrename2 as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: GET https://cloud.mongodb.com/api/atlas/v1.0/groups//clusters/testrename2: 404 (request "Not Found") Cannot find resource /api/atlas/v1.0/groups//clusters/testrename2.

**Comment by vasilevp** [comment]
The fix will be included in the upcoming release
