### ISSUE TITLE
[bug] Creating a new service key binding and selecting user roles adds ReadWrite@default role

### ISSUE THREAD

**Issue by tanjoht** [mongodb/atlas-osb#89]
When creating a new service key binding using the cf create-service-key command, the default ReadWrite@default role specified in the plan is also added.

ie:

cf create-service-key service-instance-name key-name -c '{"user" : {"roles" : [ { "roleName" : "readAnyDatabase", "databaseName" : "admin"} ] } }'

results in a new database user with readAnyDatabase role, readWrite@default role.

The expected behaviour is that only the role explicitly specified should be added.

The plan includes the following settings:

settings:
  overrideBindDB: "default"
  overrideBindDBRole: "readWrite"

**Comment by leo-ri** [comment]
Thank you for reporting
fix merged into `master` branch and will appear in a future release
